### ISSUE TITLE
[Question] deployment  jumpserver-jms-core 报错

### ISSUE THREAD

**Issue by ZH-fanlinjie** [jumpserver/helm#6]
报错如下： 我该怎么解决？
2021-08-12T13:13:05.897336013Z 2021-08-12 21:13:05 Check database connection ...
2021-08-12T13:13:06.124980935Z Traceback (most recent call last):
2021-08-12T13:13:06.125005402Z   File "manage.py", line 28, in <module>
2021-08-12T13:13:06.125011563Z     execute_from_command_line(sys.argv)
2021-08-12T13:13:06.125016209Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
2021-08-12T13:13:06.12502115Z     utility.execute()
2021-08-12T13:13:06.125025558Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
2021-08-12T13:13:06.125030106Z     self.fetch_command(subcommand).run_from_argv(self.argv)
2021-08-12T13:13:06.125034206Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
2021-08-12T13:13:06.125038563Z     self.execute(*args, **cmd_options)
2021-08-12T13:13:06.125042601Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 368, in execute
2021-08-12T13:13:06.125046942Z     self.check()
2021-08-12T13:13:06.125050962Z   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
2021-08-12T13:13:06.125055623Z     all_issues = checks.run_checks(
2021-08-12T13:13:06.125059891Z   File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
2021-08-12T13:13:06.125064483Z     new_errors = check(app_configs=app_configs, databases=databases)
2021-08-12T13:13:06.125068879Z   File "/usr/local/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 18, in check_all_models
2021-08-12T13:13:06.125073584Z     models = apps.get_models()
2021-08-12T13:13:06.125077951Z   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 179, in get_models
2021-08-12T13:13:06.125082464Z     self.check_models_ready()
2021-08-12T13:13:06.125086683Z   File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 141, in check_models_ready
2021-08-12T13:13:06.125102222Z     raise AppRegistryNotReady("Models aren't loaded yet.")
2021-08-12T13:13:06.125106898Z django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by wojiushixiaobai** [comment]
报错不完整，看起来是代码不完整导致，推测是挂载的存储有问题。
